### ISSUE TITLE
KeyError: 'getpwnam(): name not found: 33e174f0-4792-415b-afd4-3ffdf8981524'    

### ISSUE THREAD

**Issue by masedki** [jupyterhub/tmpauthenticator#12]
I am trying to deploy an environment on a server to run R notebook for students of France without authentication. I'm trying to use jupyterhub with tmpauthenticator but I'm having the following error.

KeyError: 'getpwnam(): name not found: 33e174f0-4792-415b-afd4-3ffdf8981524'    

my jupyterhub_config.py file contains: 
import tmpauthenticator
c.JupyterHub.authenticator_class = tmpauthenticator.TmpAuthenticator
c.LocalAuthenticator.create_system_users = True
c.PAMAuthenticator.open_sessions = False
c.Spawner.cmd = '/usr/local/bin/jupyterhub-singleuser'
c.Spawner.args = ['--allow-root','--no-browser']
c.Spawner.notebook_dir = '~/notebooks'
c.JupyterHub.ssl_cert = 'mycert.pem'
c.JupyterHub.ssl_key = 'mykey.key'
c.JupyterHub.cookie_secret_file = '/home/juser/jupyterhub_cookie_secret'
c.JupyterHub.proxy_cmd = ['/usr/local/bin/configurable-http-proxy']

 is there some things wrong ?

**Comment by hilhert** [comment]
I guess you should use dockerspawner or systemdspawner. Especiallly the systemdspawner and I'm figuring it out.

**Comment by hilhert** [comment]
import tmpauthenticator
import systemdspawner
c=get_config()
c.JupyterHub.authenticator_class=tmpauthenticator.TmpAuthenticator
c.JupyterHub.spawner_class=systemdspawner.SystemdSpawner
c.SystemdSpawner.dynamic_users=True
The config above works with root. But always keep reconnecting to the kernels......

**Comment by masedki** [comment]
Thank you very much, your help motivated me to relaunch this work that I left out, now I'm facing this.
![capture du 2018-10-17 17-03-11](https://user-images.githubusercontent.com/7141023/47153835-f897b800-d2e0-11e8-9177-3a97530c3236.png)

**Comment by hilhert** [comment]
**c.Spawner.notebook_dir = '~/notebooks'**
I my case, the config above cause the spanwer could not  work. So I just ask my students to git clone the class resources.  
It may take a long time to study about systemd, when we can get the default user directory copy to the temp users' directory. I think you may try  modifying '~/notebooks' to '/home/root/notebooks', and 
'/home/sedki/mycert.pem' to '/home/root/mycert.pem'
 '/home/sedki/mykey.key' to '/home/root/mykey.key'
 '/home/sedki/jupyterhub_cookie_secret' to  '/home/root/jupyterhub_cookie_secret'
root user may not have the permission to access native user's directory, some times.
please ensure you can start up and successfully log in jupyter notebook and use the kernel you want when you start your jupyter notebook with **root**.

**Comment by sridhar562345** [comment]
> **c.Spawner.notebook_dir = '~/notebooks'**
> In my case, the config above cause the spanwer could not work. So I just ask my students to git clone the class resources.
> It may take a long time to study about systemd, when we can get the default user directory copy to the temp users' directory. I think you may try modifying '~/notebooks' to '/home/root/notebooks', and
> '/home/sedki/mycert.pem' to '/home/root/mycert.pem'
> '/home/sedki/mykey.key' to '/home/root/mykey.key'
> '/home/sedki/jupyterhub_cookie_secret' to '/home/root/jupyterhub_cookie_secret'
> **root** user may not have the permission to access native user's directory, some times.
> At last, please ensure you can start up and successfully log in jupyter notebook and use the kernel you want, when you start your jupyter notebook with **root**.

Can I have a working dockerimage with tmpauthenticator enabled?
