### ISSUE TITLE
Don't start new server every time of user

### ISSUE THREAD

**Issue by IamViditAgarwal** [jupyterhub/tmpauthenticator#15]
Hi , I am using TmpAuthenticator for JupyterHub in my org . Because I dont want people to login for Jupyterhub separately , so they use the serices of Jupyter through passing my system to Jupyterhub.
But I am facing few issues which cause less user to use my platform .
Issues : 
1) In TmpAuthenticator it is written that each time it forces the server of user to terminate and end , But this cause too much time like upto 3-4 mins in some of the cases, which I want to reduce , `SO my question is that instead of forcing restart every time Cant we just create a new server when every time user logins, so this will make the whole thing pretty fast .? Because this is stopping my user to open multiple  times Jupyter Hub as it terminates the older ones`

PS : I want my user to open JupyterHub muktiple times without terminating the older instances..

Thanks in advance
Vidit

**Comment by manics** [comment]
Just wondering, what's your use case for having multiple jupyter servers per user instead of running multiple notebooks in the same server?

**Comment by sridhar562345** [comment]
can I have a working jupyterhub with jupyterhub-tmpauthenticator enabled docker image?

**Comment by manics** [comment]
@sridhar562345 please stop spamming this repository with the same question. As mentioned in other replies to your comments please use the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from answers.

**Comment by sridhar562345** [comment]
> @sridhar562345 please stop spamming this repository with the same question. As mentioned in other replies to your comments please use the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from answers.
As you mentioned I have deleted my message. But my issue was closed. Wouldn't it be nice if we add a working docker file to this repo.

**Comment by consideRatio** [comment]
I think this strategy was implemented in #22
