### ISSUE TITLE
Include import step in readme

### ISSUE THREAD

**Issue by Dommsko** [jupyterhub/tmpauthenticator#20]
Hey, I searched for hours until I found out why my setup was not working. It's not really a bug, but you might want to add `import tmpauthenticator` to the installation part of the readme file to save other users some grey hair.

Kind regards,
Dominik

**Comment by sridhar562345** [comment]
Hey, which version of jupyterhub are you using?

**Comment by consideRatio** [comment]
Thanks for reporting this, its certainly an issue with the documentation at least. Instead of fixing it with an import statement, I look to simplify the configuration via #38.
