### ISSUE TITLE
Plan release of 1.0.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/tmpauthenticator#30]
Since this repo part of JupyterHub's organization, [bundled with the z2jh distribution](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/d6bc7ab10359702e7034425428a7fd48fd3e50c8/images/hub/requirements.in#L18), and used by 2i2c in a deployment - I figure it merits some general maintenance.

### Changes blocking release

- #22
- #39, closed by #45

### Optional bonus changes

- #28, closed by #33
- #29, closed by #34
- #27, closed by #35
- #26, closed by #36 and #47
- #31, closed by #32
- #37
- #38

**Comment by consideRatio** [comment]
@yuvipanda I'd like to make this GitHub repo up to date with various jupyterhub org practices and sprint it towards 1.0.0 release for the upcoming z2jh 3.0.0 release. Does that sound okay to you?

Could you as part of https://github.com/jupyterhub/tmpauthenticator/issues/27 invite `jupyterhub-bot` to be a maintainer of the PyPI project at https://pypi.org/manage/project/jupyterhub-tmpauthenticator/collaboration/?

**Comment by manics** [comment]
https://github.com/jupyterhub/tmpauthenticator/blob/fb444abda4bc7439ff958648dc450a69a688da55/setup.py#L9
is a personal email address. Should we change it to a team/jupyter address?
