### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by takluyver** [jupyterhub/tmpauthenticator#7]
It would be good to release Yuvi's changes in #2 to make it work with 0.8.

**Comment by yuvipanda** [comment]
I've pushed out v0.5 to PyPI now! Thanks for the poke, @takluyver

**Comment by takluyver** [comment]
Thank you for the speedy response!

**Comment by willingc** [comment]
@yuvipanda Would you mind tagging the release here? Thanks for getting it on PyPI.

**Comment by takluyver** [comment]
I jumped in and made a tag :-)
